src/taskmanager/urls.py
from django.urls import path
from django.conf.urls import include

from . import views
from django.contrib.auth import views as auth_views

app_name = 'taskmanager'
urlpatterns = [
    path('', views.index, name='index'),
    path('viewlist', views.getList, name='viewlist'),
    path('viewtask', views.getTask, name='viewtask'),
    path('addnote', views.addNote, name='addnote'),
    path('addtask', views.addTask, name='addtask'),
    path('addrole', views.giveRole, name='addrole'),
    path('editend', views.editEndDate, name='editend'),
    path('claimtask', views.claimTask, name='claimtask'),
    path('deletenote', views.deleteNote, name='deletenote'),
    path('deletetask', views.deleteTask, name='deletetask'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout')
]

src/taskmanagingsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('taskmanager/', include('taskmanager.urls', namespace='taskmanager')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
]

src/taskmanager/models.py
from django.db import models
from django.core.validators import MaxLengthValidator

class Role(models.Model):
    class Meta:
        unique_together = (('role_team', 'access_level'),)

    role_team = models.CharField(max_length=100)
    access_level = models.IntegerField()
    
    def __str__(self):
        return self.role_team + " Level " + str(self.access_level)

class User(models.Model):
    email = models.CharField(max_length=100, primary_key=True)
    name = models.CharField(max_length=100)
    roles = models.ManyToManyField(Role)

    def __str__(self):
        return self.name + ": " + self.email

class List(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    can_read = models.IntegerField(null=True)
    can_claim = models.IntegerField(null=True)
    can_add = models.IntegerField(null=True)
    can_admin = models.IntegerField(null=True)
    team = models.CharField(max_length=100, null=True)
    
    def __str__(self):
        return self.name

class Task(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_tasks')
    claimants = models.ManyToManyField(User, related_name='claimed_tasks')
    title = models.CharField(max_length=10000)
    task_list = models.ForeignKey(List, on_delete=models.CASCADE, related_name='tasks')
    description = models.TextField(max_length=1000000000, validators=[MaxLengthValidator(1000000000)])
    priority = models.IntegerField()
    larger_goal = models.TextField(max_length=10000, null=True, validators=[MaxLengthValidator(10000)])
    estimate_end_date = models.DateField(null=True)

    def __str__(self):
        return self.title

class Note(models.Model):
    text = models.TextField(max_length=1000000000000, validators=[MaxLengthValidator(1000000000000)])
    poster = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='notes')
    
    def __str__(self):
        return self.text

src/taskmanager/forms.py
from django import forms
from .models import Note, Task


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['text']

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'priority', 'larger_goal']

class EndDateForm(forms.Form):
    date = forms.DateField(widget=forms.SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ),)

src/taskmanager/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
import sys

from .models import Task, List, User, Role, Note
from .forms import NoteForm, TaskForm, EndDateForm

# Create your views here.

def index(request):
        lists = []
        if request.user.is_authenticated:
                if User.objects.filter(email=request.user.email).count() == 0:
                        newUser = User(email=request.user.email, name=(request.user.first_name + request.user.last_name))
                        newUser.save()
                user = User.objects.filter(email=request.user.email)[0]
                print("found user")
                print(user.roles.all())
                for x in user.roles.all():
                        lists.extend(list(List.objects.filter(team=x.role_team, can_read__lte=x.access_level)))
       
        template = loader.get_template('taskmanager/view_lists.html')
        context = {
                'lists': lists,
                'authed': request.user.is_authenticated,
        }
        return HttpResponse(template.render(context, request))
                
                
def getList(request):
    ourList = List.objects.filter(name=request.GET.get('name', ''))[0]
    can_view = False
    can_add = False
    can_admin = False
    if request.user.is_authenticated:
            user = User.objects.filter(email=request.user.email)[0]
            for x in user.roles.all():
                if x.role_team == ourList.team:
                        if x.access_level >= ourList.can_read:
                                can_view = True
                        if x.access_level >= ourList.can_add:
                                can_add = True
                        if x.access_level >= ourList.can_admin:
                                can_admin = True

    task_list = ourList.tasks.all()
    template = loader.get_template('taskmanager/view_list.html')
    context = {
        'list_name': request.GET.get('name', ''),
        'tasks_list': task_list,
        'authed': request.user.is_authenticated,
        'can_view': can_view,
        'can_add': can_add,
        'can_admin': can_admin,
        'user': user,
    }
    return HttpResponse(template.render(context, request))
    
def getTask(request):
    task = Task.objects.filter(id=request.GET.get('id', ''))[0]
    ourList = task.task_list
    can_view = False
    can_claim = False
    can_admin = False
    if request.user.is_authenticated:
            user = User.objects.filter(email=request.user.email)[0]
            for x in user.roles.all():
                if x.role_team == ourList.team:
                        if x.access_level >= ourList.can_read:
                                can_view = True
                        if x.access_level >= ourList.can_claim:
                                can_claim = True
                        if x.access_level >= ourList.can_admin:
                                can_admin = True

    template = loader.get_template('taskmanager/view_task.html')
    context = {
        'task': task,
        'authed': request.user.is_authenticated,
        'can_view': can_view,
        'can_claim': can_claim,
        'can_admin': can_admin,
        'not_claimed': task.claimants.filter(email=request.user.email).count() == 0,
        'user': user,
    }
    return HttpResponse(template.render(context, request))

def addNote(request):
        can_claim = False
        if request.method == 'POST':
                ourList = Task.objects.filter(id=request.POST.get('task', ''))[0].task_list
                if request.user.is_authenticated:
                        user = User.objects.filter(email=request.user.email)[0]
                        for x in user.roles.all():
                                if x.role_team == ourList.team:
                                        if x.access_level >= ourList.can_claim:
                                                can_claim = True
                if not can_claim:
                        context = {
                                'authed': request.user.is_authenticated,
                        }

                        template = loader.get_template('taskmanager/denied.html')
                        return HttpResponse(template.render(context, request))
                else:
                        form = NoteForm(request.POST)
                        if form.is_valid():
                                print(form.cleaned_data, sys.stderr)
                                newNote = form.save(commit=False)
                                newNote.poster = User.objects.filter(email=request.user.email)[0]
                                newNote.task = Task.objects.filter(id=request.POST.get("task"))[0]
                                newNote.save()
                                return HttpResponseRedirect('/taskmanager/viewtask?id=' + request.POST.get("task"))
        else:
                ourList = Task.objects.filter(id=request.GET.get('task', ''))[0].task_list
                if request.user.is_authenticated:
                        user = User.objects.filter(email=request.user.email)[0]
                        for x in user.roles.all():
                                if x.role_team == ourList.team:
                                        if x.access_level >= ourList.can_claim:
                                                can_claim = True

                if not can_claim:
                        context = {
                                'authed': request.user.is_authenticated,
                        }

                        template = loader.get_template('taskmanager/denied.html')
                        return HttpResponse(template.render(context, request))
                else:
                        noteForm = NoteForm()
                        
                        context = {
                                'task': request.GET.get('task', ''),
                                'form': noteForm,
                                'authed': request.user.is_authenticated,
                        }

                        template = loader.get_template('taskmanager/add_note.html')
                        return HttpResponse(template.render(context, request))

def addTask(request):
        can_add = False
        if request.method == 'POST':
                ourList = List.objects.filter(name=request.POST.get('list', ''))[0]
                if request.user.is_authenticated:
                        user = User.objects.filter(email=request.user.email)[0]
                        for x in user.roles.all():
                                if x.role_team == ourList.team:
                                        if x.access_level >= ourList.can_add:
                                                can_add = True
                if not can_add:
                        context = {
                                'authed': request.user.is_authenticated,
                        }

                        template = loader.get_template('taskmanager/denied.html')
                        return HttpResponse(template.render(context, request))
                else:
                        form = TaskForm(request.POST)
                        if form.is_valid():
                                newTask = form.save(commit=False)
                                newTask.creator = User.objects.filter(email=request.user.email)[0]
                                newTask.task_list = List.objects.filter(name=request.POST.get('list'))[0]
                                newTask.save()
                                return HttpResponseRedirect('/taskmanager/viewlist?name=' + request.POST.get('list'))
                        else:
                             context = {
                                'authed': False,
                             }

                             template = loader.get_template('taskmanager/denied.html')
                             return HttpResponse(template.render(context, request))   
        else:
                ourList = List.objects.filter(name=request.GET.get('list', ''))[0]
                if request.user.is_authenticated:
                        user = User.objects.filter(email=request.user.email)[0]
                        for x in user.roles.all():
                                if x.role_team == ourList.team:
                                        if x.access_level >= ourList.can_add:
                                                can_add = True

                if not can_add:
                        context = {
                                'authed': request.user.is_authenticated,
                        }

                        template = loader.get_template('taskmanager/denied.html')
                        return HttpResponse(template.render(context, request))
                else:
                        taskForm = TaskForm()
                        
                        context = {
                                'list': request.GET.get('list', ''),
                                'form': taskForm,
                                'authed': request.user.is_authenticated,
                        }

                        template = loader.get_template('taskmanager/add_task.html')
                        return HttpResponse(template.render(context, request))

def deleteNote(request):
        if request.method == 'POST':
                user = User.objects.filter(email=request.user.email)[0]
                note = Note.objects.filter(id=request.POST.get('id', ''))
                can_delete = False
                ourList = Note.objects.filter(id=request.POST.get('id', ''))[0].task.task_list
                if request.user.is_authenticated:
                        for x in user.roles.all():
                                if x.role_team == ourList.team:
                                        if x.access_level >= ourList.can_admin or note.poster == user:

src/taskmanager/templates/taskmanager/add_note.html
{% extends "taskmanager/base_generic.html" %}

{% block title %}Add Note{% endblock %}

{% block content %}
<br>
<form action="/taskmanager/addnote" method="post">
	{% csrf_token %}
    {{ form }}
	<input type="hidden" value="{{ task }}" name="task">
	<input type="submit" value="Submit">
</form>
{% endblock %}

src/taskmanager/templates/taskmanager/add_role.html
{% extends "taskmanager/base_generic.html" %}

{% block title %}Assign Role{% endblock %}

{% block content %}
<br>
<script>
var dictionary = [];
{% for item, value in teamMax.items %}
	dictionary.push({key: "{{ item }}", value: "{{ value }}"});
{% endfor %}

function updateMax() {
	var e = document.getElementById("teamSel");
	if (e.selectedIndex == null) e.selectedIndex = 0;
	var selected = e.options[e.selectedIndex].value;
	for (var i = 0; i < dictionary.length; i++) {
		if (dictionary[i].key == selected) {
			selected = i;
			break;
		}
	}
	
	document.getElementById("levelAdd").max = dictionary[selected].value;
	document.getElementById("addLab").innerHTML = "Select the access level you want to assign. The maximum is " + dictionary[selected].value;
}
</script>
<form action="/taskmanager/addrole" method="post" id="roleform">
	{% csrf_token %}
	<label for="userSel">User to assign</label><br>
    <select name="targetUser" form="roleform" id="userSel">
		{% for user in allowedUsers %}
			<option value="{{ user.email }}">{{ user.name }}</option>
		{% endfor %}
	</select><br>
	<label for="teamSel">Select the team to assign the user to</label><br>
	<select name="teamSelect" form="roleform" id="teamSel" onchange="updateMax()">
		{% for team in allowedTeams %}
			<option value="{{ team }}">{{ team }}</option>
		{% endfor %}
	</select><br>
	<label for="level" id="addLab">Select the access level you want to assign</label>
	<input type="number" id="levelAdd" name="level" min="1">
	<input type="submit" value="Submit">
	<script>updateMax();</script>
</form>
{% endblock %}

src/taskmanager/templates/taskmanager/add_task.html
{% extends "taskmanager/base_generic.html" %}

{% block title %}Add Task{% endblock %}

{% block content %}
<br>
<form action="/taskmanager/addtask" method="post">
	{% csrf_token %}
    {{ form }}
	<input type="hidden" value="{{ list }}" name="list">
	<input type="submit" value="Submit">
</form>
{% endblock %}

src/taskmanager/templates/taskmanager/base_generic.html
{% load static %}

<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="{% static 'taskmanager/base_generic.css' %}">
	</head>
	<body>
		<header>
			{% block header %}
				<!-- WIP -->
			{% endblock %}
		</header>
		<nav>
			
				<ul>
					<li><a href="{% url 'taskmanager:index' %}">Home</a></li>
					{% block nav %}
					{% endblock %}
					{% if authed %}
						<li><a href="{% url 'taskmanager:logout' %}">Logout</a></li>
					{% else %}
						<li><a href="{% url 'taskmanager:login' %}">Login</a></li>
					{% endif %}
					<li><a href="{% url 'taskmanager:addrole' %}">Assign a Role</a></li>
				</ul><br>
			
		</nav>
		<br>
		{% if authed %}
			{% block content %}
			{% endblock %}
		{% else %}
			<h1><a href="{% url 'taskmanager:login' %}">Please Log In</a></h1>
		{% endif %}
		<footer>
			{% block footer %}
				<!-- WIP -->
			{% endblock %}
		</footer>
	</body>
</html>

src/taskmanager/templates/taskmanager/denied.html
{% extends "taskmanager/base_generic.html" %}

{% block title %}Denied{% endblock %}
	
{% block content %}
<br>
<h1>Denied!</h1>
<p>Please go back to home, you can't do that</p>
{% endblock %}

src/taskmanager/templates/taskmanager/edit_end.html
{% extends "taskmanager/base_generic.html" %}

{% block title %}Edit End Date{% endblock %}

{% block content %}
<br>
<form action="/taskmanager/editend" method="post">
	{% csrf_token %}
    {{ form }}
	<input type="hidden" value="{{ task }}" name="task">
	<input type="submit" value="Submit">
</form>
{% endblock %}

src/taskmanager/templates/taskmanager/view_list.html
{% extends "taskmanager/base_generic.html" %}

{% block title %}Task List: {{ list_name }}{% endblock %}
	
{% block content %}
<script>
	function getCookie(name) {
		var cookieValue = null;
		if (document.cookie && document.cookie !== '') {
			var cookies = document.cookie.split(';');
			for (var i = 0; i < cookies.length; i++) {
				var cookie = cookies[i].trim();
				// Does this cookie string begin with the name we want?
				if (cookie.substring(0, name.length + 1) === (name + '=')) {
					cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
					break;
				}
			}
		}
		return cookieValue;
	}
	
	function deleter(id) {
		var request = new XMLHttpRequest();
		var url = 'deletetask';
		var params = 'id=' + id;
		request.open('POST', url, true);
		request.setRequestHeader('X-CSRFToken', getCookie('csrftoken'));
		request.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
		
		request.onreadystatechange = function() {//Call a function when the state changes.
			if(request.readyState == 4 && request.status == 200) {
				location.reload(true);
			}
		}
		
		request.send(params)
	}
</script>
<h1>Tasks</h1>
{% if can_add %}
	<b><a href="/taskmanager/addtask?list={{ list_name }}">Add Task</a></b>
{% endif %}
<hr>
{% if can_view %}
{% for task in tasks_list %}
	<div class="task_simple">
	<a href="/taskmanager/viewtask?id={{ task.id }}"><b>{{ task.title }}</b></a>
	<p style="color:#808080">{{ task.description }}</p>
	<p>Priority: {{ task.priority }}</p>
	{% if task.claimants.count > 0 %}
		<p>Claimants: {% for claim in task.claimants.all %}{{ claim.name }} {% endfor %}
	{% endif %}
	{% if can_admin or user.email == task.creator %}
		<b><a href="javascript:deleter({{ task.id }});">Delete Task</a></b>
	{% endif %}
	<br>
	</div><hr>
{% endfor %}
{% else %}
	<b>No Access</b>
{% endif %}
{% endblock %}

src/taskmanager/templates/taskmanager/view_lists.html
{% extends "taskmanager/base_generic.html" %}

{% block title %}Task Manager: Home{% endblock %}

{% block content %}
<h1>Lists</h1>
{% for list in lists %}
	<div class='seperated'>
		<h2><a href='/taskmanager/viewlist?name={{ list.name }}'>List: {{ list.name }}</a></h2>
		<p>Team: {{ list.team }}</p>
	</div>
{% endfor %}
{% endblock %}

src/taskmanager/templates/taskmanager/view_task.html
{% extends "taskmanager/base_generic.html" %}

{% block title %}Task: {{ task.title }}{% endblock %}

{% block content %}
<script>
	function getCookie(name) {
		var cookieValue = null;
		if (document.cookie && document.cookie !== '') {
			var cookies = document.cookie.split(';');
			for (var i = 0; i < cookies.length; i++) {
				var cookie = cookies[i].trim();
				// Does this cookie string begin with the name we want?
				if (cookie.substring(0, name.length + 1) === (name + '=')) {
					cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
					break;
				}
			}
		}
		return cookieValue;
	}
	
	function deleter(id) {
		var request = new XMLHttpRequest();
		var url = 'deletenote';
		var params = 'id=' + id;
		request.open('POST', url, true);
		request.setRequestHeader('X-CSRFToken', getCookie('csrftoken'));
		request.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
		
		request.onreadystatechange = function() {//Call a function when the state changes.
			if(request.readyState == 4 && request.status == 200) {
				location.reload(true);
			}
		}
		
		request.send(params);
	}
	
	function claimer(id) {
		var request = new XMLHttpRequest();
		var url = 'claimtask';
		var params = 'id=' + id;
		request.open('POST', url, true);
		request.setRequestHeader('X-CSRFToken', getCookie('csrftoken'));
		request.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
		
		request.onreadystatechange = function() {//Call a function when the state changes.
			if(request.readyState == 4 && request.status == 200) {
				location.reload(true);
			}
		}
		
		request.send(params);
	}
</script>
{% if can_view %}
<h1>Task: {{ task.title }}</h1>
<p>Creator: {{ task.creator.name }}</p>
<p>Description: {{ task.description }}</p>
<p>Task List: <a href="/taskmanager/viewlist?name={{ task.task_list.name }}"> {{ task.task_list.name }}</a></p>
<p>Priority: {{ task.priority }}</p>
<p>Larger Goal: {{ task.larger_goal }}</p>
<p>Estimated End Date: {{ task.estimate_end_date }}</p>
{% if can_claim and not_claimed %}
	<b><a href="javascript:claimer({{ task.id }})">Claim Task</a></b>
{% endif %}
{% if not not_claimed %}
	<b><a href="/taskmanager/editend?id={{ task.id }}">Edit Expected End Date</a></b>
{% endif %}
<hr>
<h1>Notes:</h1>
<b><a href="/taskmanager/addnote?task={{ task.id }}">Add Note</a></b>
<br>
{% for note in task.notes.all|dictsort:"id" %}
	<div class="seperated">
		{% if can_admin or user.email == note.poster %}
			<b><a href="javascript:deleter({{ note.id }})">Delete</a></b>
		{% endif %}
		<p>Poster: {{ note.poster.name }}</p>
		<p>{{ note.text }}</p>
	</div>
{% endfor %}
{% else %}
<b> No Access</b>
{% endif %}
{% endblock %}